[tools]
node = "lts"
"npm:pnpm" = "latest"
go = "latest"
chezmoi = "latest"
opentofu = "latest"
gh = "latest"
golangci-lint = "latest"
stripe-cli = "latest"
uv = "latest"
yq = "latest"
yt-dlp = "latest"
opencode = "latest"
zola = "latest"
bitwarden = "latest"
"pipx:httpie" = "latest"
codex = "latest"
claude = "latest"
